// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileFormat.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "fileFormat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* BlobHeader_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BlobHeader_reflection_ = NULL;
const ::google::protobuf::Descriptor* Blob_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Blob_reflection_ = NULL;
struct BlobOneofInstance {
  ::google::protobuf::internal::ArenaStringPtr raw_;
  ::google::protobuf::internal::ArenaStringPtr zlib_data_;
  ::google::protobuf::internal::ArenaStringPtr lzma_data_;
  ::google::protobuf::internal::ArenaStringPtr obsolete_bzip2_data_;
  ::google::protobuf::internal::ArenaStringPtr lz4_data_;
  ::google::protobuf::internal::ArenaStringPtr zstd_data_;
}* Blob_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_fileFormat_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_fileFormat_2eproto() {
  protobuf_AddDesc_fileFormat_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "fileFormat.proto");
  GOOGLE_CHECK(file != NULL);
  BlobHeader_descriptor_ = file->message_type(0);
  static const int BlobHeader_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BlobHeader, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BlobHeader, indexdata_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BlobHeader, datasize_),
  };
  BlobHeader_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      BlobHeader_descriptor_,
      BlobHeader::default_instance_,
      BlobHeader_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BlobHeader, _has_bits_[0]),
      -1,
      -1,
      sizeof(BlobHeader),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BlobHeader, _internal_metadata_),
      -1);
  Blob_descriptor_ = file->message_type(1);
  static const int Blob_offsets_[8] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blob, raw_size_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, raw_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, zlib_data_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, lzma_data_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, obsolete_bzip2_data_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, lz4_data_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Blob_default_oneof_instance_, zstd_data_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blob, data_),
  };
  Blob_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Blob_descriptor_,
      Blob::default_instance_,
      Blob_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blob, _has_bits_[0]),
      -1,
      -1,
      Blob_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blob, _oneof_case_[0]),
      sizeof(Blob),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Blob, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_fileFormat_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      BlobHeader_descriptor_, &BlobHeader::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Blob_descriptor_, &Blob::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_fileFormat_2eproto() {
  delete BlobHeader::default_instance_;
  delete BlobHeader_reflection_;
  delete Blob::default_instance_;
  delete Blob_default_oneof_instance_;
  delete Blob_reflection_;
}

void protobuf_AddDesc_fileFormat_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_fileFormat_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020fileFormat.proto\"\?\n\nBlobHeader\022\014\n\004type"
    "\030\001 \002(\t\022\021\n\tindexdata\030\002 \001(\014\022\020\n\010datasize\030\003 "
    "\002(\005\"\245\001\n\004Blob\022\020\n\010raw_size\030\002 \001(\005\022\r\n\003raw\030\001 "
    "\001(\014H\000\022\023\n\tzlib_data\030\003 \001(\014H\000\022\023\n\tlzma_data\030"
    "\004 \001(\014H\000\022!\n\023OBSOLETE_bzip2_data\030\005 \001(\014B\002\030\001"
    "H\000\022\022\n\010lz4_data\030\006 \001(\014H\000\022\023\n\tzstd_data\030\007 \001("
    "\014H\000B\006\n\004data", 251);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "fileFormat.proto", &protobuf_RegisterTypes);
  BlobHeader::default_instance_ = new BlobHeader();
  Blob::default_instance_ = new Blob();
  Blob_default_oneof_instance_ = new BlobOneofInstance();
  BlobHeader::default_instance_->InitAsDefaultInstance();
  Blob::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_fileFormat_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_fileFormat_2eproto {
  StaticDescriptorInitializer_fileFormat_2eproto() {
    protobuf_AddDesc_fileFormat_2eproto();
  }
} static_descriptor_initializer_fileFormat_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BlobHeader::kTypeFieldNumber;
const int BlobHeader::kIndexdataFieldNumber;
const int BlobHeader::kDatasizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BlobHeader::BlobHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:BlobHeader)
}

void BlobHeader::InitAsDefaultInstance() {
}

BlobHeader::BlobHeader(const BlobHeader& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:BlobHeader)
}

void BlobHeader::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  indexdata_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  datasize_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BlobHeader::~BlobHeader() {
  // @@protoc_insertion_point(destructor:BlobHeader)
  SharedDtor();
}

void BlobHeader::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  indexdata_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void BlobHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BlobHeader::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BlobHeader_descriptor_;
}

const BlobHeader& BlobHeader::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_fileFormat_2eproto();
  return *default_instance_;
}

BlobHeader* BlobHeader::default_instance_ = NULL;

BlobHeader* BlobHeader::New(::google::protobuf::Arena* arena) const {
  BlobHeader* n = new BlobHeader;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BlobHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:BlobHeader)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_type()) {
      type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_indexdata()) {
      indexdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    datasize_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool BlobHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BlobHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string type = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->type().data(), this->type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "BlobHeader.type");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_indexdata;
        break;
      }

      // optional bytes indexdata = 2;
      case 2: {
        if (tag == 18) {
         parse_indexdata:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_indexdata()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_datasize;
        break;
      }

      // required int32 datasize = 3;
      case 3: {
        if (tag == 24) {
         parse_datasize:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &datasize_)));
          set_has_datasize();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BlobHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BlobHeader)
  return false;
#undef DO_
}

void BlobHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BlobHeader)
  // required string type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BlobHeader.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // optional bytes indexdata = 2;
  if (has_indexdata()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->indexdata(), output);
  }

  // required int32 datasize = 3;
  if (has_datasize()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->datasize(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:BlobHeader)
}

::google::protobuf::uint8* BlobHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:BlobHeader)
  // required string type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->type().data(), this->type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "BlobHeader.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // optional bytes indexdata = 2;
  if (has_indexdata()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->indexdata(), target);
  }

  // required int32 datasize = 3;
  if (has_datasize()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->datasize(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BlobHeader)
  return target;
}

int BlobHeader::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:BlobHeader)
  int total_size = 0;

  if (has_type()) {
    // required string type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  if (has_datasize()) {
    // required int32 datasize = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->datasize());
  }

  return total_size;
}
int BlobHeader::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:BlobHeader)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required string type = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());

    // required int32 datasize = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->datasize());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // optional bytes indexdata = 2;
  if (has_indexdata()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->indexdata());
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BlobHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BlobHeader)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const BlobHeader* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const BlobHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BlobHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BlobHeader)
    MergeFrom(*source);
  }
}

void BlobHeader::MergeFrom(const BlobHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BlobHeader)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_has_type();
      type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
    }
    if (from.has_indexdata()) {
      set_has_indexdata();
      indexdata_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.indexdata_);
    }
    if (from.has_datasize()) {
      set_datasize(from.datasize());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void BlobHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BlobHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BlobHeader::CopyFrom(const BlobHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BlobHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BlobHeader::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000005) != 0x00000005) return false;

  return true;
}

void BlobHeader::Swap(BlobHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BlobHeader::InternalSwap(BlobHeader* other) {
  type_.Swap(&other->type_);
  indexdata_.Swap(&other->indexdata_);
  std::swap(datasize_, other->datasize_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BlobHeader::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BlobHeader_descriptor_;
  metadata.reflection = BlobHeader_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BlobHeader

// required string type = 1;
bool BlobHeader::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void BlobHeader::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
void BlobHeader::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void BlobHeader::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_type();
}
 const ::std::string& BlobHeader::type() const {
  // @@protoc_insertion_point(field_get:BlobHeader.type)
  return type_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BlobHeader::set_type(const ::std::string& value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BlobHeader.type)
}
 void BlobHeader::set_type(const char* value) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BlobHeader.type)
}
 void BlobHeader::set_type(const char* value, size_t size) {
  set_has_type();
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BlobHeader.type)
}
 ::std::string* BlobHeader::mutable_type() {
  set_has_type();
  // @@protoc_insertion_point(field_mutable:BlobHeader.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BlobHeader::release_type() {
  // @@protoc_insertion_point(field_release:BlobHeader.type)
  clear_has_type();
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BlobHeader::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    set_has_type();
  } else {
    clear_has_type();
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:BlobHeader.type)
}

// optional bytes indexdata = 2;
bool BlobHeader::has_indexdata() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void BlobHeader::set_has_indexdata() {
  _has_bits_[0] |= 0x00000002u;
}
void BlobHeader::clear_has_indexdata() {
  _has_bits_[0] &= ~0x00000002u;
}
void BlobHeader::clear_indexdata() {
  indexdata_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_indexdata();
}
 const ::std::string& BlobHeader::indexdata() const {
  // @@protoc_insertion_point(field_get:BlobHeader.indexdata)
  return indexdata_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BlobHeader::set_indexdata(const ::std::string& value) {
  set_has_indexdata();
  indexdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:BlobHeader.indexdata)
}
 void BlobHeader::set_indexdata(const char* value) {
  set_has_indexdata();
  indexdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:BlobHeader.indexdata)
}
 void BlobHeader::set_indexdata(const void* value, size_t size) {
  set_has_indexdata();
  indexdata_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:BlobHeader.indexdata)
}
 ::std::string* BlobHeader::mutable_indexdata() {
  set_has_indexdata();
  // @@protoc_insertion_point(field_mutable:BlobHeader.indexdata)
  return indexdata_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* BlobHeader::release_indexdata() {
  // @@protoc_insertion_point(field_release:BlobHeader.indexdata)
  clear_has_indexdata();
  return indexdata_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void BlobHeader::set_allocated_indexdata(::std::string* indexdata) {
  if (indexdata != NULL) {
    set_has_indexdata();
  } else {
    clear_has_indexdata();
  }
  indexdata_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), indexdata);
  // @@protoc_insertion_point(field_set_allocated:BlobHeader.indexdata)
}

// required int32 datasize = 3;
bool BlobHeader::has_datasize() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void BlobHeader::set_has_datasize() {
  _has_bits_[0] |= 0x00000004u;
}
void BlobHeader::clear_has_datasize() {
  _has_bits_[0] &= ~0x00000004u;
}
void BlobHeader::clear_datasize() {
  datasize_ = 0;
  clear_has_datasize();
}
 ::google::protobuf::int32 BlobHeader::datasize() const {
  // @@protoc_insertion_point(field_get:BlobHeader.datasize)
  return datasize_;
}
 void BlobHeader::set_datasize(::google::protobuf::int32 value) {
  set_has_datasize();
  datasize_ = value;
  // @@protoc_insertion_point(field_set:BlobHeader.datasize)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Blob::kRawSizeFieldNumber;
const int Blob::kRawFieldNumber;
const int Blob::kZlibDataFieldNumber;
const int Blob::kLzmaDataFieldNumber;
const int Blob::kOBSOLETEBzip2DataFieldNumber;
const int Blob::kLz4DataFieldNumber;
const int Blob::kZstdDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Blob::Blob()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Blob)
}

void Blob::InitAsDefaultInstance() {
  Blob_default_oneof_instance_->raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  Blob_default_oneof_instance_->zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  Blob_default_oneof_instance_->lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  Blob_default_oneof_instance_->obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  Blob_default_oneof_instance_->lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  Blob_default_oneof_instance_->zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Blob::Blob(const Blob& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Blob)
}

void Blob::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  raw_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_data();
}

Blob::~Blob() {
  // @@protoc_insertion_point(destructor:Blob)
  SharedDtor();
}

void Blob::SharedDtor() {
  if (has_data()) {
    clear_data();
  }
  if (this != default_instance_) {
  }
}

void Blob::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Blob::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Blob_descriptor_;
}

const Blob& Blob::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_fileFormat_2eproto();
  return *default_instance_;
}

Blob* Blob::default_instance_ = NULL;

Blob* Blob::New(::google::protobuf::Arena* arena) const {
  Blob* n = new Blob;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Blob::clear_data() {
// @@protoc_insertion_point(one_of_clear_start:Blob)
  switch(data_case()) {
    case kRaw: {
      data_.raw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kZlibData: {
      data_.zlib_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kLzmaData: {
      data_.lzma_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kOBSOLETEBzip2Data: {
      data_.obsolete_bzip2_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kLz4Data: {
      data_.lz4_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case kZstdData: {
      data_.zstd_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = DATA_NOT_SET;
}


void Blob::Clear() {
// @@protoc_insertion_point(message_clear_start:Blob)
  raw_size_ = 0;
  clear_data();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool Blob::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Blob)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes raw = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_raw()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_raw_size;
        break;
      }

      // optional int32 raw_size = 2;
      case 2: {
        if (tag == 16) {
         parse_raw_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &raw_size_)));
          set_has_raw_size();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_zlib_data;
        break;
      }

      // optional bytes zlib_data = 3;
      case 3: {
        if (tag == 26) {
         parse_zlib_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_zlib_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_lzma_data;
        break;
      }

      // optional bytes lzma_data = 4;
      case 4: {
        if (tag == 34) {
         parse_lzma_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_lzma_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_OBSOLETE_bzip2_data;
        break;
      }

      // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
      case 5: {
        if (tag == 42) {
         parse_OBSOLETE_bzip2_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_obsolete_bzip2_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_lz4_data;
        break;
      }

      // optional bytes lz4_data = 6;
      case 6: {
        if (tag == 50) {
         parse_lz4_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_lz4_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_zstd_data;
        break;
      }

      // optional bytes zstd_data = 7;
      case 7: {
        if (tag == 58) {
         parse_zstd_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_zstd_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Blob)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Blob)
  return false;
#undef DO_
}

void Blob::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Blob)
  // optional bytes raw = 1;
  if (has_raw()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->raw(), output);
  }

  // optional int32 raw_size = 2;
  if (has_raw_size()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->raw_size(), output);
  }

  // optional bytes zlib_data = 3;
  if (has_zlib_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->zlib_data(), output);
  }

  // optional bytes lzma_data = 4;
  if (has_lzma_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->lzma_data(), output);
  }

  // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
  if (has_obsolete_bzip2_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->obsolete_bzip2_data(), output);
  }

  // optional bytes lz4_data = 6;
  if (has_lz4_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      6, this->lz4_data(), output);
  }

  // optional bytes zstd_data = 7;
  if (has_zstd_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      7, this->zstd_data(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Blob)
}

::google::protobuf::uint8* Blob::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Blob)
  // optional bytes raw = 1;
  if (has_raw()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->raw(), target);
  }

  // optional int32 raw_size = 2;
  if (has_raw_size()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->raw_size(), target);
  }

  // optional bytes zlib_data = 3;
  if (has_zlib_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->zlib_data(), target);
  }

  // optional bytes lzma_data = 4;
  if (has_lzma_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->lzma_data(), target);
  }

  // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
  if (has_obsolete_bzip2_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->obsolete_bzip2_data(), target);
  }

  // optional bytes lz4_data = 6;
  if (has_lz4_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        6, this->lz4_data(), target);
  }

  // optional bytes zstd_data = 7;
  if (has_zstd_data()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        7, this->zstd_data(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Blob)
  return target;
}

int Blob::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Blob)
  int total_size = 0;

  // optional int32 raw_size = 2;
  if (has_raw_size()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->raw_size());
  }

  switch (data_case()) {
    // optional bytes raw = 1;
    case kRaw: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->raw());
      break;
    }
    // optional bytes zlib_data = 3;
    case kZlibData: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->zlib_data());
      break;
    }
    // optional bytes lzma_data = 4;
    case kLzmaData: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->lzma_data());
      break;
    }
    // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
    case kOBSOLETEBzip2Data: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->obsolete_bzip2_data());
      break;
    }
    // optional bytes lz4_data = 6;
    case kLz4Data: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->lz4_data());
      break;
    }
    // optional bytes zstd_data = 7;
    case kZstdData: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->zstd_data());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Blob::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Blob)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Blob* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Blob>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Blob)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Blob)
    MergeFrom(*source);
  }
}

void Blob::MergeFrom(const Blob& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Blob)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  switch (from.data_case()) {
    case kRaw: {
      set_raw(from.raw());
      break;
    }
    case kZlibData: {
      set_zlib_data(from.zlib_data());
      break;
    }
    case kLzmaData: {
      set_lzma_data(from.lzma_data());
      break;
    }
    case kOBSOLETEBzip2Data: {
      set_obsolete_bzip2_data(from.obsolete_bzip2_data());
      break;
    }
    case kLz4Data: {
      set_lz4_data(from.lz4_data());
      break;
    }
    case kZstdData: {
      set_zstd_data(from.zstd_data());
      break;
    }
    case DATA_NOT_SET: {
      break;
    }
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_raw_size()) {
      set_raw_size(from.raw_size());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void Blob::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Blob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Blob::CopyFrom(const Blob& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Blob)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Blob::IsInitialized() const {

  return true;
}

void Blob::Swap(Blob* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Blob::InternalSwap(Blob* other) {
  std::swap(raw_size_, other->raw_size_);
  std::swap(data_, other->data_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Blob::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Blob_descriptor_;
  metadata.reflection = Blob_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Blob

// optional int32 raw_size = 2;
bool Blob::has_raw_size() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void Blob::set_has_raw_size() {
  _has_bits_[0] |= 0x00000001u;
}
void Blob::clear_has_raw_size() {
  _has_bits_[0] &= ~0x00000001u;
}
void Blob::clear_raw_size() {
  raw_size_ = 0;
  clear_has_raw_size();
}
 ::google::protobuf::int32 Blob::raw_size() const {
  // @@protoc_insertion_point(field_get:Blob.raw_size)
  return raw_size_;
}
 void Blob::set_raw_size(::google::protobuf::int32 value) {
  set_has_raw_size();
  raw_size_ = value;
  // @@protoc_insertion_point(field_set:Blob.raw_size)
}

// optional bytes raw = 1;
bool Blob::has_raw() const {
  return data_case() == kRaw;
}
void Blob::set_has_raw() {
  _oneof_case_[0] = kRaw;
}
void Blob::clear_raw() {
  if (has_raw()) {
    data_.raw_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::raw() const {
  // @@protoc_insertion_point(field_get:Blob.raw)
  if (has_raw()) {
    return data_.raw_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_raw(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.raw)
  if (!has_raw()) {
    clear_data();
    set_has_raw();
    data_.raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.raw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.raw)
}
 void Blob::set_raw(const char* value) {
  if (!has_raw()) {
    clear_data();
    set_has_raw();
    data_.raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.raw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.raw)
}
 void Blob::set_raw(const void* value, size_t size) {
  if (!has_raw()) {
    clear_data();
    set_has_raw();
    data_.raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.raw_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.raw)
}
 ::std::string* Blob::mutable_raw() {
  if (!has_raw()) {
    clear_data();
    set_has_raw();
    data_.raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.raw)
  return data_.raw_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_raw() {
  // @@protoc_insertion_point(field_release:Blob.raw)
  if (has_raw()) {
    clear_has_data();
    return data_.raw_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_raw(::std::string* raw) {
  if (!has_raw()) {
    data_.raw_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (raw != NULL) {
    set_has_raw();
    data_.raw_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        raw);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.raw)
}

// optional bytes zlib_data = 3;
bool Blob::has_zlib_data() const {
  return data_case() == kZlibData;
}
void Blob::set_has_zlib_data() {
  _oneof_case_[0] = kZlibData;
}
void Blob::clear_zlib_data() {
  if (has_zlib_data()) {
    data_.zlib_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::zlib_data() const {
  // @@protoc_insertion_point(field_get:Blob.zlib_data)
  if (has_zlib_data()) {
    return data_.zlib_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_zlib_data(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.zlib_data)
  if (!has_zlib_data()) {
    clear_data();
    set_has_zlib_data();
    data_.zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zlib_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.zlib_data)
}
 void Blob::set_zlib_data(const char* value) {
  if (!has_zlib_data()) {
    clear_data();
    set_has_zlib_data();
    data_.zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zlib_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.zlib_data)
}
 void Blob::set_zlib_data(const void* value, size_t size) {
  if (!has_zlib_data()) {
    clear_data();
    set_has_zlib_data();
    data_.zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zlib_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.zlib_data)
}
 ::std::string* Blob::mutable_zlib_data() {
  if (!has_zlib_data()) {
    clear_data();
    set_has_zlib_data();
    data_.zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.zlib_data)
  return data_.zlib_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_zlib_data() {
  // @@protoc_insertion_point(field_release:Blob.zlib_data)
  if (has_zlib_data()) {
    clear_has_data();
    return data_.zlib_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_zlib_data(::std::string* zlib_data) {
  if (!has_zlib_data()) {
    data_.zlib_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (zlib_data != NULL) {
    set_has_zlib_data();
    data_.zlib_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        zlib_data);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.zlib_data)
}

// optional bytes lzma_data = 4;
bool Blob::has_lzma_data() const {
  return data_case() == kLzmaData;
}
void Blob::set_has_lzma_data() {
  _oneof_case_[0] = kLzmaData;
}
void Blob::clear_lzma_data() {
  if (has_lzma_data()) {
    data_.lzma_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::lzma_data() const {
  // @@protoc_insertion_point(field_get:Blob.lzma_data)
  if (has_lzma_data()) {
    return data_.lzma_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_lzma_data(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.lzma_data)
  if (!has_lzma_data()) {
    clear_data();
    set_has_lzma_data();
    data_.lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lzma_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.lzma_data)
}
 void Blob::set_lzma_data(const char* value) {
  if (!has_lzma_data()) {
    clear_data();
    set_has_lzma_data();
    data_.lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lzma_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.lzma_data)
}
 void Blob::set_lzma_data(const void* value, size_t size) {
  if (!has_lzma_data()) {
    clear_data();
    set_has_lzma_data();
    data_.lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lzma_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.lzma_data)
}
 ::std::string* Blob::mutable_lzma_data() {
  if (!has_lzma_data()) {
    clear_data();
    set_has_lzma_data();
    data_.lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.lzma_data)
  return data_.lzma_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_lzma_data() {
  // @@protoc_insertion_point(field_release:Blob.lzma_data)
  if (has_lzma_data()) {
    clear_has_data();
    return data_.lzma_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_lzma_data(::std::string* lzma_data) {
  if (!has_lzma_data()) {
    data_.lzma_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (lzma_data != NULL) {
    set_has_lzma_data();
    data_.lzma_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        lzma_data);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.lzma_data)
}

// optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
bool Blob::has_obsolete_bzip2_data() const {
  return data_case() == kOBSOLETEBzip2Data;
}
void Blob::set_has_obsolete_bzip2_data() {
  _oneof_case_[0] = kOBSOLETEBzip2Data;
}
void Blob::clear_obsolete_bzip2_data() {
  if (has_obsolete_bzip2_data()) {
    data_.obsolete_bzip2_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::obsolete_bzip2_data() const {
  // @@protoc_insertion_point(field_get:Blob.OBSOLETE_bzip2_data)
  if (has_obsolete_bzip2_data()) {
    return data_.obsolete_bzip2_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_obsolete_bzip2_data(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.OBSOLETE_bzip2_data)
  if (!has_obsolete_bzip2_data()) {
    clear_data();
    set_has_obsolete_bzip2_data();
    data_.obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.obsolete_bzip2_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.OBSOLETE_bzip2_data)
}
 void Blob::set_obsolete_bzip2_data(const char* value) {
  if (!has_obsolete_bzip2_data()) {
    clear_data();
    set_has_obsolete_bzip2_data();
    data_.obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.obsolete_bzip2_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.OBSOLETE_bzip2_data)
}
 void Blob::set_obsolete_bzip2_data(const void* value, size_t size) {
  if (!has_obsolete_bzip2_data()) {
    clear_data();
    set_has_obsolete_bzip2_data();
    data_.obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.obsolete_bzip2_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.OBSOLETE_bzip2_data)
}
 ::std::string* Blob::mutable_obsolete_bzip2_data() {
  if (!has_obsolete_bzip2_data()) {
    clear_data();
    set_has_obsolete_bzip2_data();
    data_.obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.OBSOLETE_bzip2_data)
  return data_.obsolete_bzip2_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_obsolete_bzip2_data() {
  // @@protoc_insertion_point(field_release:Blob.OBSOLETE_bzip2_data)
  if (has_obsolete_bzip2_data()) {
    clear_has_data();
    return data_.obsolete_bzip2_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_obsolete_bzip2_data(::std::string* obsolete_bzip2_data) {
  if (!has_obsolete_bzip2_data()) {
    data_.obsolete_bzip2_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (obsolete_bzip2_data != NULL) {
    set_has_obsolete_bzip2_data();
    data_.obsolete_bzip2_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        obsolete_bzip2_data);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.OBSOLETE_bzip2_data)
}

// optional bytes lz4_data = 6;
bool Blob::has_lz4_data() const {
  return data_case() == kLz4Data;
}
void Blob::set_has_lz4_data() {
  _oneof_case_[0] = kLz4Data;
}
void Blob::clear_lz4_data() {
  if (has_lz4_data()) {
    data_.lz4_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::lz4_data() const {
  // @@protoc_insertion_point(field_get:Blob.lz4_data)
  if (has_lz4_data()) {
    return data_.lz4_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_lz4_data(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.lz4_data)
  if (!has_lz4_data()) {
    clear_data();
    set_has_lz4_data();
    data_.lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lz4_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.lz4_data)
}
 void Blob::set_lz4_data(const char* value) {
  if (!has_lz4_data()) {
    clear_data();
    set_has_lz4_data();
    data_.lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lz4_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.lz4_data)
}
 void Blob::set_lz4_data(const void* value, size_t size) {
  if (!has_lz4_data()) {
    clear_data();
    set_has_lz4_data();
    data_.lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.lz4_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.lz4_data)
}
 ::std::string* Blob::mutable_lz4_data() {
  if (!has_lz4_data()) {
    clear_data();
    set_has_lz4_data();
    data_.lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.lz4_data)
  return data_.lz4_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_lz4_data() {
  // @@protoc_insertion_point(field_release:Blob.lz4_data)
  if (has_lz4_data()) {
    clear_has_data();
    return data_.lz4_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_lz4_data(::std::string* lz4_data) {
  if (!has_lz4_data()) {
    data_.lz4_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (lz4_data != NULL) {
    set_has_lz4_data();
    data_.lz4_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        lz4_data);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.lz4_data)
}

// optional bytes zstd_data = 7;
bool Blob::has_zstd_data() const {
  return data_case() == kZstdData;
}
void Blob::set_has_zstd_data() {
  _oneof_case_[0] = kZstdData;
}
void Blob::clear_zstd_data() {
  if (has_zstd_data()) {
    data_.zstd_data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_data();
  }
}
 const ::std::string& Blob::zstd_data() const {
  // @@protoc_insertion_point(field_get:Blob.zstd_data)
  if (has_zstd_data()) {
    return data_.zstd_data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Blob::set_zstd_data(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:Blob.zstd_data)
  if (!has_zstd_data()) {
    clear_data();
    set_has_zstd_data();
    data_.zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zstd_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Blob.zstd_data)
}
 void Blob::set_zstd_data(const char* value) {
  if (!has_zstd_data()) {
    clear_data();
    set_has_zstd_data();
    data_.zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zstd_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Blob.zstd_data)
}
 void Blob::set_zstd_data(const void* value, size_t size) {
  if (!has_zstd_data()) {
    clear_data();
    set_has_zstd_data();
    data_.zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  data_.zstd_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Blob.zstd_data)
}
 ::std::string* Blob::mutable_zstd_data() {
  if (!has_zstd_data()) {
    clear_data();
    set_has_zstd_data();
    data_.zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:Blob.zstd_data)
  return data_.zstd_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Blob::release_zstd_data() {
  // @@protoc_insertion_point(field_release:Blob.zstd_data)
  if (has_zstd_data()) {
    clear_has_data();
    return data_.zstd_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Blob::set_allocated_zstd_data(::std::string* zstd_data) {
  if (!has_zstd_data()) {
    data_.zstd_data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_data();
  if (zstd_data != NULL) {
    set_has_zstd_data();
    data_.zstd_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        zstd_data);
  }
  // @@protoc_insertion_point(field_set_allocated:Blob.zstd_data)
}

bool Blob::has_data() const {
  return data_case() != DATA_NOT_SET;
}
void Blob::clear_has_data() {
  _oneof_case_[0] = DATA_NOT_SET;
}
Blob::DataCase Blob::data_case() const {
  return Blob::DataCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
